dist: xenial
sudo: required
language: c

cache:
  directories:
    - $HOME/.conan/

install:
  - wget https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_7_2.deb
  - sudo dpkg -i conan-ubuntu-64_1_7_2.deb
  - conan user
  - conan remote add ror-dependencies https://api.bintray.com/conan/anotherfoxguy/ror-dependencies || true

script:
  - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CONAN=TRUE .
  - make -j2
